import React, { useState } from 'react';
import { 
  CheckCircle2, 
  Check, 
  Copy, 
  Download, 
  AlertTriangle
} from 'lucide-react';
import { IntegrationRisk, ReviewStatus } from '../types';

interface ResolutionCenterTabProps {
  risks: IntegrationRisk[];
  selectedRiskId: string;
  onSelectRisk: (id: string) => void;
  onReviewRisk: (id: string, status: ReviewStatus, notes?: string) => void;
}

export const ResolutionCenterTab: React.FC<ResolutionCenterTabProps> = ({
  risks,
  selectedRiskId,
  onSelectRisk,
  onReviewRisk
}) => {
  const currentRisk = risks.find((r) => r.id === selectedRiskId) || risks[0];
  const [copied, setCopied] = useState<boolean>(false);
  const [notes, setNotes] = useState<string>(currentRisk?.review_notes || '');
  const [completedSteps, setCompletedSteps] = useState<number[]>([]);

  if (!currentRisk) {
    return <div className="p-8 text-center text-gray-500 font-mono text-xs">No active risks detected.</div>;
  }

  const toggleStep = (stepNumber: number) => {
    if (completedSteps.includes(stepNumber)) {
      setCompletedSteps(completedSteps.filter((s) => s !== stepNumber));
    } else {
      setCompletedSteps([...completedSteps, stepNumber]);
    }
  };

  const generateMarkdownReport = () => {
    return `# MergeMind Resolution Advisory: ${currentRisk.title}
**Risk Level**: ${currentRisk.risk_level} (Score: ${currentRisk.risk_score.total}/100)
**Branches Involved**: \`${currentRisk.branches[0]}\` and \`${currentRisk.branches[1]}\`
**Status**: ${currentRisk.review_status}

## PROBLEM STATEMENT
${currentRisk.summary}

## AFFECTED COMPONENTS
${currentRisk.affected_components.map((c) => `- ${c}`).join('\n')}

## AFFECTED REPOSITORY FILES
${currentRisk.affected_files.map((f) => `- \`${f}\``).join('\n')}

## RECOMMENDED RESOLUTION PROCEDURE
${currentRisk.recommended_steps
  .map((s) => `${s.step_number}. **${s.action}**\n   ${s.detail}${s.file_reference ? ` (Reference: \`${s.file_reference}\`)` : ''}`)
  .join('\n\n')}

## TECHNICAL RATIONALE
${currentRisk.why_it_exists}

## POTENTIAL PRODUCTION IMPACT
${currentRisk.potential_impact}

## REQUIRED TEST VERIFICATION
Framework: ${currentRisk.test_recommendation.tooling_detected}
Commands:
\`\`\`bash
${currentRisk.test_recommendation.test_commands.join('\n')}
\`\`\`

---
*Generated by MergeMind Integration Advisor — Human Developer Verification Required*
`;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdownReport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportMarkdown = () => {
    const text = generateMarkdownReport();
    const blob = new Blob([text], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mergemind-resolution-${currentRisk.id}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4">
      {/* Risk Ribbon */}
      <div className="p-2.5 rounded-lg bg-[#161b22] border border-[#30363d] flex items-center gap-2 overflow-x-auto text-xs font-mono">
        <span className="text-gray-500 whitespace-nowrap pl-1 text-[11px]">TARGET RISK:</span>
        {risks.map((r) => {
          const isSelected = r.id === currentRisk.id;
          return (
            <button
              key={r.id}
              onClick={() => onSelectRisk(r.id)}
              className={`px-2.5 py-1 rounded whitespace-nowrap transition-colors flex items-center gap-2 ${
                isSelected
                  ? 'bg-[#21262d] text-white border border-gray-600 font-semibold'
                  : 'text-gray-400 hover:text-gray-200'
              }`}
            >
              <span className={`w-1.5 h-1.5 rounded-full ${r.risk_level === 'CRITICAL' ? 'bg-red-500' : 'bg-amber-500'}`} />
              <span className="max-w-[200px] truncate">{r.title}</span>
              {r.review_status === 'REVIEWED' && (
                <Check className="w-3 h-3 text-emerald-400" />
              )}
            </button>
          );
        })}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        
        {/* Left 2 Cols: Step-by-Step Resolution */}
        <div className="lg:col-span-2 space-y-4">
          
          <div className="p-5 rounded-lg bg-[#161b22] border border-[#30363d] space-y-4">
            <div className="flex flex-wrap items-start justify-between gap-3 pb-3 border-b border-[#30363d]">
              <div>
                <div className="flex items-center gap-2 mb-1 font-mono text-[11px]">
                  <span className="px-1.5 py-0.2 rounded bg-[#0d1117] text-gray-400 border border-[#30363d]">
                    AGENT 6 RESOLUTION PROCEDURE
                  </span>
                  <span className="text-gray-500">
                    {currentRisk.branches[0]} ↔ {currentRisk.branches[1]}
                  </span>
                </div>
                <h3 className="text-base font-semibold text-white">
                  {currentRisk.title}
                </h3>
              </div>

              <div className="flex items-center gap-2">
                <button
                  onClick={handleCopyMarkdown}
                  className="px-2.5 py-1 rounded bg-[#21262d] hover:bg-[#30363d] text-gray-200 text-xs font-mono border border-[#30363d] transition-colors flex items-center gap-1.5"
                >
                  {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3 text-gray-400" />}
                  {copied ? 'Copied' : 'Copy Plan'}
                </button>
                <button
                  onClick={handleExportMarkdown}
                  className="px-2.5 py-1 rounded bg-[#21262d] hover:bg-[#30363d] text-gray-200 text-xs font-mono border border-[#30363d] transition-colors flex items-center gap-1.5"
                >
                  <Download className="w-3 h-3 text-gray-400" />
                  Export .md
                </button>
              </div>
            </div>

            {/* Problem Box */}
            <div className="p-3.5 rounded bg-[#0d1117] border border-[#30363d] space-y-1 text-xs">
              <div className="text-red-400 font-mono text-[10px] uppercase font-bold flex items-center gap-1.5">
                <AlertTriangle className="w-3.5 h-3.5" />
                <span>Problem Statement</span>
              </div>
              <p className="text-gray-300 text-xs leading-relaxed">
                {currentRisk.summary}
              </p>
            </div>

            {/* Affected Meta */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs font-mono">
              <div className="p-3 rounded bg-[#0d1117] border border-[#30363d] space-y-1">
                <span className="text-gray-500 text-[10px] uppercase">AFFECTED COMPONENTS</span>
                <div className="flex flex-wrap gap-1 pt-0.5">
                  {currentRisk.affected_components.map((c) => (
                    <span key={c} className="px-1.5 py-0.2 rounded bg-[#161b22] text-gray-300 border border-[#30363d] text-[11px]">
                      {c}
                    </span>
                  ))}
                </div>
              </div>

              <div className="p-3 rounded bg-[#0d1117] border border-[#30363d] space-y-1">
                <span className="text-gray-500 text-[10px] uppercase">TARGET FILES</span>
                <div className="flex flex-wrap gap-1 pt-0.5">
                  {currentRisk.affected_files.map((f) => (
                    <span key={f} className="px-1.5 py-0.2 rounded bg-[#161b22] text-blue-300 border border-[#30363d] text-[11px]">
                      {f}
                    </span>
                  ))}
                </div>
              </div>
            </div>

            {/* Step-by-Step Procedure */}
            <div className="space-y-2.5 pt-1">
              <div className="flex items-center justify-between text-xs font-mono text-gray-400">
                <span>ACTION STEPS ({completedSteps.length} OF {currentRisk.recommended_steps.length} VERIFIED)</span>
                <span className="text-[11px] text-gray-500">Check off as implemented</span>
              </div>

              <div className="space-y-2">
                {currentRisk.recommended_steps.map((step) => {
                  const isDone = completedSteps.includes(step.step_number);

                  return (
                    <div
                      key={step.step_number}
                      onClick={() => toggleStep(step.step_number)}
                      className={`p-3.5 rounded border transition-colors cursor-pointer flex items-start gap-3 ${
                        isDone
                          ? 'bg-[#161b22]/40 border-gray-800 opacity-60'
                          : 'bg-[#0d1117] border-[#30363d] hover:border-gray-500'
                      }`}
                    >
                      <div className="pt-0.5">
                        <div
                          className={`w-4 h-4 rounded flex items-center justify-center border transition-colors ${
                            isDone
                              ? 'bg-emerald-700 border-emerald-600 text-white'
                              : 'border-gray-600 text-transparent'
                          }`}
                        >
                          <Check className="w-3 h-3 stroke-[3]" />
                        </div>
                      </div>

                      <div className="space-y-1 text-xs flex-1">
                        <div className="flex items-center justify-between">
                          <span className={`font-semibold ${isDone ? 'line-through text-gray-500' : 'text-gray-200'}`}>
                            {step.step_number}. {step.action}
                          </span>
                          {step.file_reference && (
                            <span className="font-mono text-[10px] px-1.5 py-0.2 rounded bg-[#161b22] text-gray-400 border border-[#30363d]">
                              {step.file_reference}
                            </span>
                          )}
                        </div>

                        <p className={`text-xs leading-relaxed font-sans ${isDone ? 'text-gray-500' : 'text-gray-400'}`}>
                          {step.detail}
                        </p>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Technical Rationale */}
            <div className="p-3 rounded bg-[#0d1117] border border-[#30363d] text-xs space-y-1">
              <span className="text-gray-500 font-mono text-[10px] uppercase block">
                Technical Rationale:
              </span>
              <p className="text-gray-300 leading-relaxed font-sans text-xs">
                {currentRisk.why_it_exists}
              </p>
            </div>
          </div>
        </div>

        {/* Right 1 Col: Human Developer Approval Gate */}
        <div className="space-y-4">
          <div className="p-4 rounded-lg bg-[#161b22] border border-[#30363d] space-y-3">
            <div className="border-b border-[#30363d] pb-2">
              <div className="text-xs font-mono font-semibold text-white">HUMAN VERIFICATION GATE</div>
              <div className="text-[11px] text-gray-400">Developer signoff required before pull request merge</div>
            </div>

            <div className="text-xs space-y-1 font-mono">
              <span className="text-gray-500 text-[10px]">CURRENT STATE:</span>
              <div className="font-bold">
                {currentRisk.review_status === 'REVIEWED' && (
                  <span className="text-emerald-400 flex items-center gap-1.5">
                    <Check className="w-3.5 h-3.5" /> REVIEWED & SIGNED OFF
                  </span>
                )}
                {currentRisk.review_status === 'DISMISSED' && (
                  <span className="text-gray-400">DISMISSED</span>
                )}
                {currentRisk.review_status === 'PENDING' && (
                  <span className="text-amber-400 flex items-center gap-1.5">
                    <AlertTriangle className="w-3.5 h-3.5" /> PENDING DEVELOPER REVIEW
                  </span>
                )}
              </div>
            </div>

            <div className="space-y-1 text-xs">
              <label className="text-gray-400 text-[11px] font-mono">SIGNOFF NOTES / RATIONALE:</label>
              <textarea
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                placeholder="e.g. Verified middleware execution order in server.js; all pipeline tests passing."
                rows={4}
                className="w-full p-2 rounded bg-[#0d1117] border border-[#30363d] text-gray-200 text-xs font-mono focus:outline-none"
              />
            </div>

            <div className="space-y-1.5 pt-1">
              <button
                onClick={() => onReviewRisk(currentRisk.id, 'REVIEWED', notes || 'Reviewed and approved by developer.')}
                className="w-full py-2 rounded bg-[#238636] hover:bg-[#2ea043] text-white font-medium text-xs transition-colors flex items-center justify-center gap-1.5"
              >
                <Check className="w-3.5 h-3.5" />
                Sign Off & Mark Reviewed
              </button>

              <button
                onClick={() => onReviewRisk(currentRisk.id, 'DISMISSED', notes || 'Risk dismissed as non-critical.')}
                className="w-full py-1.5 rounded bg-[#21262d] hover:bg-[#30363d] text-gray-400 border border-[#30363d] text-xs transition-colors"
              >
                Dismiss Risk
              </button>
            </div>

            <p className="text-[10px] text-gray-500 font-mono text-center">
              System does not auto-merge. Human approval mandatory.
            </p>
          </div>
        </div>

      </div>
    </div>
  );
};
